name: Liquibase Workflow

on: [workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Run Liquibase Update
      uses: liquibase/liquibase-github-action@v7
      with:
        operation: 'update'
        changeLogFile: 'liquibase/changelog.xml'
        url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=true;trustServerCertificate=true
        username: sa
        password: ${{ secrets.SQLSERVER_PASSWORD }}
        
